name: wiki
version: "2.1"
services:
  mariadb:
    image: lscr.io/linuxserver/mariadb:latest
    container_name: mariadb
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=rootPassword
      - TZ=America/Chicago
      - MYSQL_DATABASE=wikijs
      - MYSQL_USER=wikijs
      - MYSQL_PASSWORD=wikijs
      #- REMOTE_SQL=http://URL1/your.sql,https://URL2/your.sql #optional
    volumes:
      - ./mariadb/config:/config
    expose:
      - 3306
    #ports:
    #  - 3306:3306
    restart: unless-stopped
    networks:
    - backend
  nginx:
    image: lscr.io/linuxserver/nginx:latest
    container_name: nginx
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - ./nginx/config:/config
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
    networks:
    - backend
    - frontend
  wikijs:
    image: lscr.io/linuxserver/wikijs:latest
    container_name: wikijs
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - ./wikijs/config:/config
      - ./wikijs/data:/data
    expose:
      - 3000
    #ports:
    #  - 3000:3000
    restart: unless-stopped
    networks:
    - backend
networks:
  frontend:
    internal: true
  backend:
